### ISSUE TITLE
Image in quay has incorrect tag for 0.1.53

### ISSUE THREAD

**Issue by stujb** [ComplianceAsCode/compliance-operator#63]
The tag for the image for release v0.1.53 at https://quay.io/repository/compliance-operator/compliance-operator?tab=tags is prefixed with a `v` but the operator deployment is looking for an image without the `v` 

```    
containerStatuses:
    - image: quay.io/compliance-operator/compliance-operator:0.1.53
      imageID: ""
      lastState: {}
      name: compliance-operator
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: 'rpc error: code = Unknown desc = reading manifest 0.1.53 in quay.io/compliance-operator/compliance-operator:
            manifest unknown: manifest unknown'
          reason: ErrImagePull
```

All previous images do not have the `v` prefix on the image tag
